### ISSUE TITLE
Bug when running onlineCPD with an object computed in a previous run

### ISSUE THREAD

**Issue by eva-gitup** [cran/ocp#1]
When onlineCPD is run with oCPD argument, the **check for compatible settings stops the running**.

`onlineCPD(datapts, oCPD=oCPD,...)`

The **indexing in the parameter list** of the new oCPD (ocpd_settings) object **does not correspond** to the indexing of the parameters oCPD (oCPD$ocpd_settings) computed in the previous run.

Therefore the following condition is false.

` if(!identical(as.character(oCPD$ocpd_settings[c(-1, -2)]), as.character(ocpd_settings[c(-1, -2)])))`

And the running returns 

```
Error in as.character(ocpd_settings[[set_id]]) : 
  cannot coerce type 'closure' to vector of type 'character'
```

**Example**
```{r}
set.seed(1)
simdatapts<- c(rnorm(n = 50), rnorm(n=50, 100))
sim1 <- simdatapts[1:50]
sim2 <- simdatapts[51:100]
ocpd1 <- onlineCPD(sim1)
ocpd2 <- onlineCPD(datapts = sim2, oCPD = ocpd1)
```
OnlineCPD function is applied on sim1 and a changepoint is detected at index 1. 
New observations sim2 are added to sim1 and a changepoint at index 51 should be detected. 

**However**, when the function runs to define ocpd2, it constructs the ocpd_setting so that :
```
> as.character(ocpd_settings[c(-1, -2)])
[1] "list(list(m = 0, k = 0.01, a = 0.01, b = 1e-04))"               "function (x, lambda) \n{\n    const_hazard(x, lambda = 100)\n}"
[3] "0.5"                                                            "2.2250738585072e-308"     
```

And ocpd1 (=oCPD) settings gives : 
```
as.character(oCPD$ocpd_settings[c(-1, -2)])
[1] "list(\"g\")"                                                    "list(list(m = 0, k = 0.01, a = 0.01, b = 1e-04))"              
[3] "function (x, lambda) \n{\n    const_hazard(x, lambda = 100)\n}" "0.5"                                                           
[5] "2.2250738585072e-308"  
```

Package : version 0.1.1
rstudioapi::versionInfo()$version : ‘1.2.5042’

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!
